spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/giftservice_dev
    username: giftservice
    password: giftservice
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.giftservice: DEBUG
    org.springframework.web: DEBUG