spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/giftservice}
    username: ${DATABASE_USERNAME:giftservice}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: false

logging:
  level:
    com.giftservice: INFO
    org.springframework.web: WARN