spring:
  datasource:
    url: jdbc:tc:postgresql:15:///test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  flyway:
    locations: classpath:db/migration
    clean-disabled: false

logging:
  level:
    com.giftservice: DEBUG
    org.testcontainers: DEBUG